In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/DieCasting_Quality_Raw_Data.csv',header=[0,1])
df

      Process                                                     \
           id Product_Type Shot Velocity_1 Velocity_2 Velocity_3
0           1            1    1      0.144      0.170      0.188
1        1002            1    2      0.144      0.170      0.182
2        2003            1    3      0.144      0.170      0.182
3        3004            1    4      0.144      0.170      0.182
4        4005            1    5      0.144      0.172      0.176
...       ...          ...  ...        ...        ...        ...
7530  7530659            2  659      0.150      0.166      0.210
7531  7531660            2  660      0.144      0.174      0.206
7532  7532660            2  660      0.144      0.174      0.206
7533  7533661            2  661      0.147      0.174      0.204
7534  7534661            2  661      0.147      0.174      0.204

                                                                         ...  \
     High_Velocity Cylinder_Pressure Rapid_Rise_Time Biscuit_Thickness   ...
0            2.134               214           0.008                 10  ...
1            2.124               217           0.008                 11  ...
2            2.116               214           0.008                 11  ...
3            2.137               217           0.008                 11  ...
4            2.111               217           0.008                 12  ...
...            ...               ...             ...                ...  ...
7530         2.492               265           0.011                 17  ...
7531         2.514               264           0.011                 16  ...
7532         2.514               264           0.011                 16  ...
7533         2.532               265           0.012                 18  ...
7534         2.532               265           0.012                 18  ...

         Defects                                                          \
     Blow_Hole_2 Stain_2 Dent_2 Deformation_2 Contamination_2 Impurity_2
0              0       0      0             0               0          0
1              0       0      0             0               0          0
2              0       0      0             0               0          0
3              0       0      0             0               0          0
4              0       0      0             0               0          0
...          ...     ...    ...           ...             ...        ...
7530           0       0      0             0               0          0
7531           0       0      0             0               0          0
7532           0       0      0             0               0          0
7533           0       0      0             0               0          0
7534           0       0      0             0               0          0


     Crack_2 Scratch_2 Buring_Mark_2 Inclusions_2
0          0         0             0            0
1          0         0             0            0
2          0         0             0            0
3          0         0             0            0
4          0         0             0            0
...      ...       ...           ...          ...
7530       0         0             0            0
7531       0         0             0            0
7532       0         0             0            0
7533       0         0             0            0
7534       0         0             0            0

[7535 rows x 57 columns]

In [3]:
df.T

                                  0         1         2         3     \
Process id                       1.000  1002.000  2003.000  3004.000
        Product_Type             1.000     1.000     1.000     1.000
        Shot                     1.000     2.000     3.000     4.000
        Velocity_1               0.144     0.144     0.144     0.144
        Velocity_2               0.170     0.170     0.170     0.170
        Velocity_3               0.188     0.182     0.182     0.182
        High_Velocity            2.134     2.124     2.116     2.137
        Cylinder_Pressure      214.000   217.000   214.000   217.000
        Rapid_Rise_Time          0.008     0.008     0.008     0.008
        Biscuit_Thickness       10.000    11.000    11.000    11.000
        Clamping_Force         258.000   257.000   257.000   257.000
        Cycle_Time              20.700    20.700    20.800    20.700
         Pressure_Rise_Time      0.044     0.044     0.041     0.043
        Casting_Pressure      1037.000  1052.000  1037.000  1051.000
        Spray_Time               7.800     7.800     7.800     7.800
        Spray_1_Time             0.700     0.700     0.700     0.700
        Spray_2_Time             0.800     0.800     0.800     0.800
Sensor  Melting_Furnace_Temp   695.000   696.400   696.400   696.400
        Air_Pressure             6.300     6.300     6.300     6.300
        Air_Pressure_Min         3.000     3.000     3.000     3.000
        Air_Pressure_Max         9.000     9.000     9.000     9.000
        Coolant_Temp            26.000    26.100    26.100    26.100
        Coolant_Temp_Min        10.000    10.000    10.000    10.000
        Coolant_Temp_Max        50.000    50.000    50.000    50.000
        Coolant_Pressure         2.710     2.690     2.690     2.690
        Factory_Temp            32.900    32.900    32.900    32.900
        Factory_Temp_Min        18.000    18.000    18.000    18.000
        Factory_Temp_Max        22.000    22.000    22.000    22.000
        Factory_Humidity        58.400    58.200    58.200    58.200
        Factory_Humidity_Min    18.000    18.000    18.000    18.000
        Factory_Humidity_Max    22.000    22.000    22.000    22.000
Defects Short_Shot_1             0.000     0.000     0.000     0.000
        Bubble_1                 0.000     0.000     0.000     0.000
        Exfoliation_1            0.000     0.000     0.000     1.000
        Blow_Hole_1              0.000     0.000     0.000     0.000
        Stain_1                  0.000     0.000     0.000     0.000
        Dent_1                   0.000     0.000     0.000     0.000
        Deformation_1            0.000     0.000     0.000     0.000
        Contamination_1          0.000     0.000     0.000     0.000
        Impurity_1               0.000     0.000     0.000     0.000
        Crack_1                  0.000     0.000     0.000     0.000
        Scratch_1                0.000     0.000     0.000     0.000
        Buring_Mark_1            0.000     0.000     0.000     0.000
        Inclusions_1             0.000     0.000     0.000     0.000
        Short_Shot_2             0.000     0.000     0.000     0.000
        Bubble_2                 0.000     0.000     0.000     0.000
        Exfoliation_2            0.000     0.000     0.000     0.000
        Blow_Hole_2              0.000     0.000     0.000     0.000
        Stain_2                  0.000     0.000     0.000     0.000
        Dent_2                   0.000     0.000     0.000     0.000
        Deformation_2            0.000     0.000     0.000     0.000
        Contamination_2          0.000     0.000     0.000     0.000
        Impurity_2               0.000     0.000     0.000     0.000
        Crack_2                  0.000     0.000     0.000     0.000
        Scratch_2                0.000     0.000     0.000     0.000
        Buring_Mark_2            0.000     0.000     0.000     0.000
        Inclusions_2             0.000     0.000     0.000     0.000

                                  4         5         6         7     \
Process id                    4005.000  5006.000  6008.000  7009.000
        Product_Type             1.000     1.000     1.000     1.000
        Shot                     5.000     6.000     8.000     9.000
        Velocity_1               0.144     0.144     0.141     0.142
        Velocity_2               0.172     0.172     0.168     0.172
        Velocity_3               0.176     0.176     0.178     0.176
        High_Velocity            2.111     2.111     2.159     2.114
        Cylinder_Pressure      217.000   217.000   214.000   217.000
        Rapid_Rise_Time          0.008     0.008     0.008     0.008
        Biscuit_Thickness       12.000    12.000    11.000    12.000
        Clamping_Force         257.000   257.000   257.000   257.000
        Cycle_Time              20.700    20.700    20.600    20.700
         Pressure_Rise_Time      0.042     0.042     0.042     0.041
        Casting_Pressure      1052.000  1052.000  1036.000  1052.000
        Spray_Time               7.800     7.800     7.800     7.800
        Spray_1_Time             0.700     0.700     0.700     0.700
        Spray_2_Time             0.800     0.800     0.800     0.800
Sensor  Melting_Furnace_Temp   697.900   697.900   699.600   699.600
        Air_Pressure             6.400     6.400     6.400     6.400
        Air_Pressure_Min         3.000     3.000     3.000     3.000
        Air_Pressure_Max         9.000     9.000     9.000     9.000
        Coolant_Temp            26.100    26.100    26.100    26.100
        Coolant_Temp_Min        10.000    10.000    10.000    10.000
        Coolant_Temp_Max        50.000    50.000    50.000    50.000
        Coolant_Pressure         2.690     2.690     2.710     2.710
        Factory_Temp            32.900    32.900    32.900    32.900
        Factory_Temp_Min        18.000    18.000    18.000    18.000
        Factory_Temp_Max        22.000    22.000    22.000    22.000
        Factory_Humidity        57.800    57.800    57.800    57.800
        Factory_Humidity_Min    18.000    18.000    18.000    18.000
        Factory_Humidity_Max    22.000    22.000    22.000    22.000
Defects Short_Shot_1             0.000     0.000     0.000     0.000
        Bubble_1                 0.000     0.000     0.000     0.000
        Exfoliation_1            0.000     0.000     0.000     0.000
        Blow_Hole_1              0.000     0.000     0.000     0.000
        Stain_1                  0.000     0.000     0.000     0.000
        Dent_1                   0.000     0.000     0.000     0.000
        Deformation_1            0.000     0.000     0.000     0.000
        Contamination_1          0.000     0.000     0.000     0.000
        Impurity_1               0.000     0.000     0.000     0.000
        Crack_1                  0.000     0.000     0.000     0.000
        Scratch_1                0.000     0.000     0.000     0.000
        Buring_Mark_1            0.000     0.000     0.000     0.000
        Inclusions_1             0.000     0.000     0.000     0.000
        Short_Shot_2             0.000     0.000     0.000     0.000
        Bubble_2                 0.000     0.000     0.000     0.000
        Exfoliation_2            0.000     0.000     0.000     0.000
        Blow_Hole_2              0.000     0.000     0.000     0.000
        Stain_2                  0.000     0.000     0.000     0.000
        Dent_2                   0.000     0.000     0.000     0.000
        Deformation_2            0.000     0.000     0.000     0.000
        Contamination_2          0.000     0.000     0.000     0.000
        Impurity_2               0.000     0.000     0.000     0.000
        Crack_2                  0.000     0.000     0.000     0.000
        Scratch_2                0.000     0.000     0.000     0.000
        Buring_Mark_2            0.000     0.000     0.000     0.000
        Inclusions_2             0.000     0.000     0.000     0.000

                                  8         9     ...         7525  \
Process id                    8010.000  9011.000  ...  7525657.000
        Product_Type             1.000     1.000  ...        2.000
        Shot                    10.000    11.000  ...      657.000
        Velocity_1               0.142     0.144  ...        0.144
        Velocity_2               0.172     0.168  ...        0.173
        Velocity_3               0.176     0.184  ...        0.200
        High_Velocity            2.114     2.145  ...        2.536
        Cylinder_Pressure      217.000   217.000  ...      264.000
        Rapid_Rise_Time          0.008     0.008  ...        0.012
        Biscuit_Thickness       12.000    11.000  ...       17.000
        Clamping_Force         257.000   257.000  ...      381.000
        Cycle_Time              20.700    20.700  ...       36.300
         Pressure_Rise_Time      0.041     0.042  ...        0.036
        Casting_Pressure      1052.000  1051.000  ...      595.000
        Spray_Time               7.800     7.800  ...       12.100
        Spray_1_Time             0.700     0.700  ...        2.000
        Spray_2_Time             0.800     0.800  ...        2.000
Sensor  Melting_Furnace_Temp   699.600   701.400  ...      666.800
        Air_Pressure             6.400     6.500  ...        6.700
        Air_Pressure_Min         3.000     3.000  ...        3.000
        Air_Pressure_Max         9.000     9.000  ...        9.000
        Coolant_Temp            26.100    26.100  ...       28.100
        Coolant_Temp_Min        10.000    10.000  ...       10.000
        Coolant_Temp_Max        50.000    50.000  ...       50.000
        Coolant_Pressure         2.710     2.710  ...        2.630
        Factory_Temp            32.900    32.900  ...       32.400
        Factory_Temp_Min        18.000    18.000  ...       18.000
        Factory_Temp_Max        22.000    22.000  ...       22.000
        Factory_Humidity        57.800    57.900  ...       69.300
        Factory_Humidity_Min    18.000    18.000  ...       18.000
        Factory_Humidity_Max    22.000    22.000  ...       22.000
Defects Short_Shot_1             0.000     0.000  ...        0.000
        Bubble_1                 0.000     0.000  ...        0.000
        Exfoliation_1            0.000     0.000  ...        0.000
        Blow_Hole_1              0.000     0.000  ...        0.000
        Stain_1                  0.000     0.000  ...        0.000
        Dent_1                   0.000     0.000  ...        0.000
        Deformation_1            0.000     1.000  ...        0.000
        Contamination_1          0.000     0.000  ...        0.000
        Impurity_1               0.000     0.000  ...        0.000
        Crack_1                  0.000     0.000  ...        0.000
        Scratch_1                0.000     0.000  ...        0.000
        Buring_Mark_1            0.000     0.000  ...        0.000
        Inclusions_1             0.000     0.000  ...        0.000
        Short_Shot_2             0.000     0.000  ...        0.000
        Bubble_2                 0.000     0.000  ...        0.000
        Exfoliation_2            0.000     0.000  ...        0.000
        Blow_Hole_2              0.000     0.000  ...        0.000
        Stain_2                  0.000     0.000  ...        0.000
        Dent_2                   0.000     0.000  ...        0.000
        Deformation_2            0.000     0.000  ...        0.000
        Contamination_2          0.000     0.000  ...        0.000
        Impurity_2               0.000     0.000  ...        0.000
        Crack_2                  0.000     0.000  ...        0.000
        Scratch_2                0.000     0.000  ...        0.000
        Buring_Mark_2            0.000     0.000  ...        0.000
        Inclusions_2             0.000     0.000  ...        0.000

                                     7526         7527         7528  \
Process id                    7526657.000  7527658.000  7528658.000
        Product_Type                2.000        2.000        2.000
        Shot                      657.000      658.000      658.000
        Velocity_1                  0.144        0.144        0.144
        Velocity_2                  0.173        0.173        0.173
        Velocity_3                  0.200        0.200        0.200
        High_Velocity               2.536        2.536        2.536
        Cylinder_Pressure         264.000      264.000      264.000
        Rapid_Rise_Time             0.012        0.012        0.012
        Biscuit_Thickness          17.000       17.000       17.000
        Clamping_Force            381.000      381.000      381.000
        Cycle_Time                 36.300       36.300       36.300
         Pressure_Rise_Time         0.036        0.036        0.036
        Casting_Pressure          595.000      595.000      595.000
        Spray_Time                 12.100       12.100       12.100
        Spray_1_Time                2.000        2.000        2.000
        Spray_2_Time                2.000        2.000        2.000
Sensor  Melting_Furnace_Temp      666.800      667.400      667.400
        Air_Pressure                6.700        6.700        6.700
        Air_Pressure_Min            3.000        3.000        3.000
        Air_Pressure_Max            9.000        9.000        9.000
        Coolant_Temp               28.100       28.100       28.100
        Coolant_Temp_Min           10.000       10.000       10.000
        Coolant_Temp_Max           50.000       50.000       50.000
        Coolant_Pressure            2.630        2.620        2.620
        Factory_Temp               32.400       32.300       32.300
        Factory_Temp_Min           18.000       18.000       18.000
        Factory_Temp_Max           22.000       22.000       22.000
        Factory_Humidity           69.300       69.400       69.400
        Factory_Humidity_Min       18.000       18.000       18.000
        Factory_Humidity_Max       22.000       22.000       22.000
Defects Short_Shot_1                0.000        0.000        0.000
        Bubble_1                    0.000        0.000        0.000
        Exfoliation_1               0.000        0.000        0.000
        Blow_Hole_1                 0.000        0.000        0.000
        Stain_1                     0.000        0.000        0.000
        Dent_1                      0.000        0.000        0.000
        Deformation_1               0.000        0.000        0.000
        Contamination_1             0.000        0.000        0.000
        Impurity_1                  0.000        0.000        0.000
        Crack_1                     0.000        0.000        0.000
        Scratch_1                   0.000        0.000        0.000
        Buring_Mark_1               0.000        0.000        0.000
        Inclusions_1                0.000        0.000        0.000
        Short_Shot_2                0.000        0.000        0.000
        Bubble_2                    0.000        0.000        0.000
        Exfoliation_2               0.000        0.000        0.000
        Blow_Hole_2                 0.000        0.000        0.000
        Stain_2                     0.000        0.000        0.000
        Dent_2                      0.000        0.000        0.000
        Deformation_2               0.000        0.000        0.000
        Contamination_2             0.000        0.000        0.000
        Impurity_2                  0.000        0.000        0.000
        Crack_2                     0.000        0.000        0.000
        Scratch_2                   0.000        0.000        0.000
        Buring_Mark_2               0.000        0.000        0.000
        Inclusions_2                0.000        0.000        0.000

                                     7529         7530         7531  \
Process id                    7529659.000  7530659.000  7531660.000
        Product_Type                2.000        2.000        2.000
        Shot                      659.000      659.000      660.000
        Velocity_1                  0.150        0.150        0.144
        Velocity_2                  0.166        0.166        0.174
        Velocity_3                  0.210        0.210        0.206
        High_Velocity               2.492        2.492        2.514
        Cylinder_Pressure         265.000      265.000      264.000
        Rapid_Rise_Time             0.011        0.011        0.011
        Biscuit_Thickness          17.000       17.000       16.000
        Clamping_Force            381.000      381.000      381.000
        Cycle_Time                 36.200       36.200       36.200
         Pressure_Rise_Time         0.033        0.033        0.041
        Casting_Pressure          595.000      595.000      595.000
        Spray_Time                 12.100       12.100       12.100
        Spray_1_Time                2.000        2.000        2.000
        Spray_2_Time                2.000        2.000        2.000
Sensor  Melting_Furnace_Temp      667.400      667.400      667.800
        Air_Pressure                6.700        6.700        7.000
        Air_Pressure_Min            3.000        3.000        3.000
        Air_Pressure_Max            9.000        9.000        9.000
        Coolant_Temp               28.100       28.100       28.100
        Coolant_Temp_Min           10.000       10.000       10.000
        Coolant_Temp_Max           50.000       50.000       50.000
        Coolant_Pressure            2.620        2.620        2.620
        Factory_Temp               32.300       32.300       32.200
        Factory_Temp_Min           18.000       18.000       18.000
        Factory_Temp_Max           22.000       22.000       22.000
        Factory_Humidity           69.400       69.400       69.500
        Factory_Humidity_Min       18.000       18.000       18.000
        Factory_Humidity_Max       22.000       22.000       22.000
Defects Short_Shot_1                0.000        0.000        0.000
        Bubble_1                    0.000        0.000        0.000
        Exfoliation_1               0.000        0.000        0.000
        Blow_Hole_1                 0.000        0.000        1.000
        Stain_1                     0.000        0.000        0.000
        Dent_1                      0.000        0.000        0.000
        Deformation_1               0.000        0.000        0.000
        Contamination_1             0.000        0.000        0.000
        Impurity_1                  0.000        0.000        0.000
        Crack_1                     0.000        0.000        0.000
        Scratch_1                   0.000        0.000        0.000
        Buring_Mark_1               0.000        0.000        0.000
        Inclusions_1                0.000        0.000        0.000
        Short_Shot_2                0.000        0.000        0.000
        Bubble_2                    0.000        0.000        0.000
        Exfoliation_2               0.000        0.000        0.000
        Blow_Hole_2                 0.000        0.000        0.000
        Stain_2                     0.000        0.000        0.000
        Dent_2                      0.000        0.000        0.000
        Deformation_2               0.000        0.000        0.000
        Contamination_2             0.000        0.000        0.000
        Impurity_2                  0.000        0.000        0.000
        Crack_2                     0.000        0.000        0.000
        Scratch_2                   0.000        0.000        0.000
        Buring_Mark_2               0.000        0.000        0.000
        Inclusions_2                0.000        0.000        0.000

                                     7532         7533         7534
Process id                    7532660.000  7533661.000  7534661.000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7535 entries, 0 to 7534
Data columns (total 57 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   (Process, id)                   7535 non-null   int64
 1   (Process, Product_Type)         7535 non-null   int64
 2   (Process, Shot)                 7535 non-null   int64
 3   (Process, Velocity_1)           7535 non-null   float64
 4   (Process, Velocity_2)           7535 non-null   float64
 5   (Process, Velocity_3)           7535 non-null   float64
 6   (Process, High_Velocity)        7535 non-null   float64
 7   (Process, Cylinder_Pressure)    7535 non-null   int64
 8   (Process, Rapid_Rise_Time)      7535 non-null   float64
 9   (Process, Biscuit_Thickness )   7535 non-null   int64
 10  (Process, Clamping_Force )      7535 non-null   int64
 11  (Process, Cycle_Time)           7535 non-null   float64
 12  (Process,  Pressure_Rise_Time)  7535 non-null   float64
 13  (Process, Casting_Pressure)     7535 non-null   int64
 14  (Process, Spray_Time)           7535 non-null   float64
 15  (Process, Spray_1_Time)         7535 non-null   float64
 16  (Process, Spray_2_Time)         7535 non-null   float64
 17  (Sensor, Melting_Furnace_Temp)  7535 non-null   float64
 18  (Sensor, Air_Pressure)          7535 non-null   float64
 19  (Sensor, Air_Pressure_Min)      7535 non-null   int64
 20  (Sensor, Air_Pressure_Max)      7535 non-null   int64
 21  (Sensor, Coolant_Temp)          7535 non-null   float64
 22  (Sensor, Coolant_Temp_Min)      7535 non-null   int64
 23  (Sensor, Coolant_Temp_Max)      7535 non-null   int64
 24  (Sensor, Coolant_Pressure)      7535 non-null   float64
 25  (Sensor, Factory_Temp)          7445 non-null   float64
 26  (Sensor, Factory_Temp_Min)      7445 non-null   float64
 27  (Sensor, Factory_Temp_Max)      7445 non-null   float64
 28  (Sensor, Factory_Humidity)      7445 non-null   float64
 29  (Sensor, Factory_Humidity_Min)  7445 non-null   float64
 30  (Sensor, Factory_Humidity_Max)  7445 non-null   float64
 31  (Defects, Short_Shot_1)         7535 non-null   int64
 32  (Defects, Bubble_1)             7535 non-null   int64
 33  (Defects, Exfoliation_1)        7535 non-null   int64
 34  (Defects, Blow_Hole_1)          7535 non-null   int64
 35  (Defects, Stain_1)              7535 non-null   int64
 36  (Defects, Dent_1)               7535 non-null   int64
 37  (Defects, Deformation_1)        7535 non-null   int64
 38  (Defects, Contamination_1)      7535 non-null   int64
 39  (Defects, Impurity_1)           7535 non-null   int64
 40  (Defects, Crack_1)              7535 non-null   int64
 41  (Defects, Scratch_1)            7535 non-null   int64
 42  (Defects, Buring_Mark_1)        7535 non-null   int64
 43  (Defects, Inclusions_1)         7535 non-null   int64
 44  (Defects, Short_Shot_2)         7535 non-null   int64
 45  (Defects, Bubble_2)             7535 non-null   int64
 46  (Defects, Exfoliation_2)        7535 non-null   int64
 47  (Defects, Blow_Hole_2)          7535 non-null   int64
 48  (Defects, Stain_2)              7535 non-null   int64
 49  (Defects, Dent_2)               7535 non-null   int64
 50  (Defects, Deformation_2)        7535 non-null   int64
 51  (Defects, Contamination_2)      7535 non-null   int64
 52  (Defects, Impurity_2)           7535 non-null   int64
 53  (Defects, Crack_2)              7535 non-null   int64
 54  (Defects, Scratch_2)            7535 non-null   int64
 55  (Defects, Buring_Mark_2)        7535 non-null   int64
 56  (Defects, Inclusions_2)         7535 non-null   int64
dtypes: float64(20), int64(37)
memory usage: 3.3 MB

In [5]:
df.shape

(7535, 57)

전처리
- 결측치는 중앙값으로
- 2,3은 1로 처리

In [6]:
# 컬럼별 결측치 개수 합계
print(df.isnull().sum())

Process  id                       0
         Product_Type             0
         Shot                     0
         Velocity_1               0
         Velocity_2               0
         Velocity_3               0
         High_Velocity            0
         Cylinder_Pressure        0
         Rapid_Rise_Time          0
         Biscuit_Thickness        0
         Clamping_Force           0
         Cycle_Time               0
          Pressure_Rise_Time      0
         Casting_Pressure         0
         Spray_Time               0
         Spray_1_Time             0
         Spray_2_Time             0
Sensor   Melting_Furnace_Temp     0
         Air_Pressure             0
         Air_Pressure_Min         0
         Air_Pressure_Max         0
         Coolant_Temp             0
         Coolant_Temp_Min         0
         Coolant_Temp_Max         0
         Coolant_Pressure         0
         Factory_Temp            90
         Factory_Temp_Min        90
         Factory_Temp_Max        90
         Factory_Humidity        90
         Factory_Humidity_Min    90
         Factory_Humidity_Max    90
Defects  Short_Shot_1             0
         Bubble_1                 0
         Exfoliation_1            0
         Blow_Hole_1              0
         Stain_1                  0
         Dent_1                   0
         Deformation_1            0
         Contamination_1          0
         Impurity_1               0
         Crack_1                  0
         Scratch_1                0
         Buring_Mark_1            0
         Inclusions_1             0
         Short_Shot_2             0
         Bubble_2                 0
         Exfoliation_2            0
         Blow_Hole_2              0
         Stain_2                  0
         Dent_2                   0
         Deformation_2            0
         Contamination_2          0
         Impurity_2               0
         Crack_2                  0
         Scratch_2                0
         Buring_Mark_2            0
         Inclusions_2             0
dtype: int64

In [7]:
### 결측치 중앙값으로

In [8]:
df_copy = df.copy()

In [9]:
df['Sensor', 'Factory_Temp'].describe()

count    7445.000000
mean       32.829684
std         1.674896
min        27.400000
25%        31.900000
50%        32.100000
75%        33.800000
max        37.000000
Name: (Sensor, Factory_Temp), dtype: float64

In [10]:
df_copy['Sensor', 'Factory_Temp'] = df['Sensor', 'Factory_Temp'].fillna(df['Sensor', 'Factory_Temp'].median())

In [11]:
df_copy['Sensor', 'Factory_Temp'].describe()

count    7535.000000
mean       32.820969
std         1.666748
min        27.400000
25%        31.900000
50%        32.100000
75%        33.700000
max        37.000000
Name: (Sensor, Factory_Temp), dtype: float64

In [12]:
df['Sensor', 'Factory_Temp_Max'].describe()

count    7445.0
mean       22.0
std         0.0
min        22.0
25%        22.0
50%        22.0
75%        22.0
max        22.0
Name: (Sensor, Factory_Temp_Max), dtype: float64

In [13]:
df_copy['Sensor', 'Factory_Temp_Max'] = df['Sensor', 'Factory_Temp_Max'].fillna(df['Sensor', 'Factory_Temp_Max'].median())

In [14]:
df_copy['Sensor', 'Factory_Temp_Max'].describe()

count    7535.0
mean       22.0
std         0.0
min        22.0
25%        22.0
50%        22.0
75%        22.0
max        22.0
Name: (Sensor, Factory_Temp_Max), dtype: float64

In [15]:
df['Sensor', 'Factory_Temp_Min'].describe()

count    7445.0
mean       18.0
std         0.0
min        18.0
25%        18.0
50%        18.0
75%        18.0
max        18.0
Name: (Sensor, Factory_Temp_Min), dtype: float64

In [16]:
df_copy['Sensor', 'Factory_Temp_Min'] = df['Sensor', 'Factory_Temp_Min'].fillna(df['Sensor', 'Factory_Temp_Min'].median())

In [17]:
df['Sensor', 'Factory_Humidity'].describe()

count    7445.000000
mean       61.673002
std         7.031202
min        45.500000
25%        58.000000
50%        63.000000
75%        66.800000
max        72.300000
Name: (Sensor, Factory_Humidity), dtype: float64

In [18]:
df_copy['Sensor', 'Factory_Humidity'] = df['Sensor', 'Factory_Humidity'].fillna(df['Sensor', 'Factory_Humidity'].median())

In [19]:
df['Sensor', 'Factory_Humidity_Max'].describe()

count    7445.0
mean       22.0
std         0.0
min        22.0
25%        22.0
50%        22.0
75%        22.0
max        22.0
Name: (Sensor, Factory_Humidity_Max), dtype: float64

In [20]:
df_copy['Sensor', 'Factory_Humidity_Max'] = df['Sensor', 'Factory_Humidity_Max'].fillna(df['Sensor', 'Factory_Humidity_Max'].median())

In [21]:
df['Sensor', 'Factory_Humidity_Min'].describe()

count    7445.0
mean       18.0
std         0.0
min        18.0
25%        18.0
50%        18.0
75%        18.0
max        18.0
Name: (Sensor, Factory_Humidity_Min), dtype: float64

In [22]:
df_copy['Sensor', 'Factory_Humidity_Min'] = df['Sensor', 'Factory_Humidity_Min'].fillna(df['Sensor', 'Factory_Humidity_Min'].median())

In [23]:
df_copy['Sensor', 'Factory_Temp'] = df['Sensor', 'Factory_Temp'].fillna(df['Sensor', 'Factory_Temp'].median())
df_copy['Sensor', 'Factory_Temp_Max'] = df['Sensor', 'Factory_Temp_Max'].fillna(df['Sensor', 'Factory_Temp_Max'].median())
df_copy['Sensor', 'Factory_Temp_Min'] = df['Sensor', 'Factory_Temp_Min'].fillna(df['Sensor', 'Factory_Temp_Min'].median())
df_copy['Sensor', 'Factory_Humidity'] = df['Sensor', 'Factory_Humidity'].fillna(df['Sensor', 'Factory_Humidity'].median())
df_copy['Sensor', 'Factory_Humidity_Max'] = df['Sensor', 'Factory_Humidity_Max'].fillna(df['Sensor', 'Factory_Humidity_Max'].median())
df_copy['Sensor', 'Factory_Humidity_Min'] = df['Sensor', 'Factory_Humidity_Min'].fillna(df['Sensor', 'Factory_Humidity_Min'].median())

In [24]:
print(df_copy.isnull().sum())

Process  id                      0
         Product_Type            0
         Shot                    0
         Velocity_1              0
         Velocity_2              0
         Velocity_3              0
         High_Velocity           0
         Cylinder_Pressure       0
         Rapid_Rise_Time         0
         Biscuit_Thickness       0
         Clamping_Force          0
         Cycle_Time              0
          Pressure_Rise_Time     0
         Casting_Pressure        0
         Spray_Time              0
         Spray_1_Time            0
         Spray_2_Time            0
Sensor   Melting_Furnace_Temp    0
         Air_Pressure            0
         Air_Pressure_Min        0
         Air_Pressure_Max        0
         Coolant_Temp            0
         Coolant_Temp_Min        0
         Coolant_Temp_Max        0
         Coolant_Pressure        0
         Factory_Temp            0
         Factory_Temp_Min        0
         Factory_Temp_Max        0
         Factory_Humidity        0
         Factory_Humidity_Min    0
         Factory_Humidity_Max    0
Defects  Short_Shot_1            0
         Bubble_1                0
         Exfoliation_1           0
         Blow_Hole_1             0
         Stain_1                 0
         Dent_1                  0
         Deformation_1           0
         Contamination_1         0
         Impurity_1              0
         Crack_1                 0
         Scratch_1               0
         Buring_Mark_1           0
         Inclusions_1            0
         Short_Shot_2            0
         Bubble_2                0
         Exfoliation_2           0
         Blow_Hole_2             0
         Stain_2                 0
         Dent_2                  0
         Deformation_2           0
         Contamination_2         0
         Impurity_2              0
         Crack_2                 0
         Scratch_2               0
         Buring_Mark_2           0
         Inclusions_2            0
dtype: int64

In [25]:
# 불량품 관련 컬럼(Defects) 중 값이 '2'인 컬럼과 갯수 출력
defect_cols = df['Defects'].columns

result = {}
for col in defect_cols:
    count = (df[('Defects', col)] >= 2).sum()
    if count > 0:
        result[col] = count

if result:
    print("값이 2 이상인 Defects 컬럼 목록:")
    for col, count in result.items():
        print(f"  {col}: {count}개")
else:
    print("값이 2인 Defects 컬럼이 없습니다.")

값이 2 이상인 Defects 컬럼 목록:
  Short_Shot_1: 15개
  Exfoliation_1: 2개
  Blow_Hole_1: 22개
  Stain_1: 20개
  Deformation_1: 1개
  Short_Shot_2: 2개
  Bubble_2: 2개
  Exfoliation_2: 3개
  Blow_Hole_2: 6개
  Deformation_2: 1개

In [26]:
defect_cols = df_copy['Defects'].columns

# 'Defects' 대분류 아래의 모든 컬럼에 대해 2 이상의 값을 1로 변경
for col in defect_cols:
    # Defects 하위의 col 값 중 2 이상인 경우를 1로 치환
    df_copy.loc[df_copy[('Defects', col)] >= 2, ('Defects', col)] = 1

In [27]:
# 불량품 관련 컬럼(Defects) 중 값이 '2'인 컬럼과 갯수 출력
defect_cols = df_copy['Defects'].columns

result = {}
for col in defect_cols:
    count = (df_copy[('Defects', col)] >= 2).sum()
    if count > 0:
        result[col] = count

if result:
    print("값이 2 이상인 Defects 컬럼 목록:")
    for col, count in result.items():
        print(f"  {col}: {count}개")
else:
    print("값이 2인 Defects 컬럼이 없습니다.")

값이 2인 Defects 컬럼이 없습니다.

In [28]:
df_copy.T

                                  0         1         2         3     \
Process id                       1.000  1002.000  2003.000  3004.000
        Product_Type             1.000     1.000     1.000     1.000
        Shot                     1.000     2.000     3.000     4.000
        Velocity_1               0.144     0.144     0.144     0.144
        Velocity_2               0.170     0.170     0.170     0.170
        Velocity_3               0.188     0.182     0.182     0.182
        High_Velocity            2.134     2.124     2.116     2.137
        Cylinder_Pressure      214.000   217.000   214.000   217.000
        Rapid_Rise_Time          0.008     0.008     0.008     0.008
        Biscuit_Thickness       10.000    11.000    11.000    11.000
        Clamping_Force         258.000   257.000   257.000   257.000
        Cycle_Time              20.700    20.700    20.800    20.700
         Pressure_Rise_Time      0.044     0.044     0.041     0.043
        Casting_Pressure      1037.000  1052.000  1037.000  1051.000
        Spray_Time               7.800     7.800     7.800     7.800
        Spray_1_Time             0.700     0.700     0.700     0.700
        Spray_2_Time             0.800     0.800     0.800     0.800
Sensor  Melting_Furnace_Temp   695.000   696.400   696.400   696.400
        Air_Pressure             6.300     6.300     6.300     6.300
        Air_Pressure_Min         3.000     3.000     3.000     3.000
        Air_Pressure_Max         9.000     9.000     9.000     9.000
        Coolant_Temp            26.000    26.100    26.100    26.100
        Coolant_Temp_Min        10.000    10.000    10.000    10.000
        Coolant_Temp_Max        50.000    50.000    50.000    50.000
        Coolant_Pressure         2.710     2.690     2.690     2.690
        Factory_Temp            32.900    32.900    32.900    32.900
        Factory_Temp_Min        18.000    18.000    18.000    18.000
        Factory_Temp_Max        22.000    22.000    22.000    22.000
        Factory_Humidity        58.400    58.200    58.200    58.200
        Factory_Humidity_Min    18.000    18.000    18.000    18.000
        Factory_Humidity_Max    22.000    22.000    22.000    22.000
Defects Short_Shot_1             0.000     0.000     0.000     0.000
        Bubble_1                 0.000     0.000     0.000     0.000
        Exfoliation_1            0.000     0.000     0.000     1.000
        Blow_Hole_1              0.000     0.000     0.000     0.000
        Stain_1                  0.000     0.000     0.000     0.000
        Dent_1                   0.000     0.000     0.000     0.000
        Deformation_1            0.000     0.000     0.000     0.000
        Contamination_1          0.000     0.000     0.000     0.000
        Impurity_1               0.000     0.000     0.000     0.000
        Crack_1                  0.000     0.000     0.000     0.000
        Scratch_1                0.000     0.000     0.000     0.000
        Buring_Mark_1            0.000     0.000     0.000     0.000
        Inclusions_1             0.000     0.000     0.000     0.000
        Short_Shot_2             0.000     0.000     0.000     0.000
        Bubble_2                 0.000     0.000     0.000     0.000
        Exfoliation_2            0.000     0.000     0.000     0.000
        Blow_Hole_2              0.000     0.000     0.000     0.000
        Stain_2                  0.000     0.000     0.000     0.000
        Dent_2                   0.000     0.000     0.000     0.000
        Deformation_2            0.000     0.000     0.000     0.000
        Contamination_2          0.000     0.000     0.000     0.000
        Impurity_2               0.000     0.000     0.000     0.000
        Crack_2                  0.000     0.000     0.000     0.000
        Scratch_2                0.000     0.000     0.000     0.000
        Buring_Mark_2            0.000     0.000     0.000     0.000
        Inclusions_2             0.000     0.000     0.000     0.000

                                  4         5         6         7     \
Process id                    4005.000  5006.000  6008.000  7009.000
        Product_Type             1.000     1.000     1.000     1.000
        Shot                     5.000     6.000     8.000     9.000
        Velocity_1               0.144     0.144     0.141     0.142
        Velocity_2               0.172     0.172     0.168     0.172
        Velocity_3               0.176     0.176     0.178     0.176
        High_Velocity            2.111     2.111     2.159     2.114
        Cylinder_Pressure      217.000   217.000   214.000   217.000
        Rapid_Rise_Time          0.008     0.008     0.008     0.008
        Biscuit_Thickness       12.000    12.000    11.000    12.000
        Clamping_Force         257.000   257.000   257.000   257.000
        Cycle_Time              20.700    20.700    20.600    20.700
         Pressure_Rise_Time      0.042     0.042     0.042     0.041
        Casting_Pressure      1052.000  1052.000  1036.000  1052.000
        Spray_Time               7.800     7.800     7.800     7.800
        Spray_1_Time             0.700     0.700     0.700     0.700
        Spray_2_Time             0.800     0.800     0.800     0.800
Sensor  Melting_Furnace_Temp   697.900   697.900   699.600   699.600
        Air_Pressure             6.400     6.400     6.400     6.400
        Air_Pressure_Min         3.000     3.000     3.000     3.000
        Air_Pressure_Max         9.000     9.000     9.000     9.000
        Coolant_Temp            26.100    26.100    26.100    26.100
        Coolant_Temp_Min        10.000    10.000    10.000    10.000
        Coolant_Temp_Max        50.000    50.000    50.000    50.000
        Coolant_Pressure         2.690     2.690     2.710     2.710
        Factory_Temp            32.900    32.900    32.900    32.900
        Factory_Temp_Min        18.000    18.000    18.000    18.000
        Factory_Temp_Max        22.000    22.000    22.000    22.000
        Factory_Humidity        57.800    57.800    57.800    57.800
        Factory_Humidity_Min    18.000    18.000    18.000    18.000
        Factory_Humidity_Max    22.000    22.000    22.000    22.000
Defects Short_Shot_1             0.000     0.000     0.000     0.000
        Bubble_1                 0.000     0.000     0.000     0.000
        Exfoliation_1            0.000     0.000     0.000     0.000
        Blow_Hole_1              0.000     0.000     0.000     0.000
        Stain_1                  0.000     0.000     0.000     0.000
        Dent_1                   0.000     0.000     0.000     0.000
        Deformation_1            0.000     0.000     0.000     0.000
        Contamination_1          0.000     0.000     0.000     0.000
        Impurity_1               0.000     0.000     0.000     0.000
        Crack_1                  0.000     0.000     0.000     0.000
        Scratch_1                0.000     0.000     0.000     0.000
        Buring_Mark_1            0.000     0.000     0.000     0.000
        Inclusions_1             0.000     0.000     0.000     0.000
        Short_Shot_2             0.000     0.000     0.000     0.000
        Bubble_2                 0.000     0.000     0.000     0.000
        Exfoliation_2            0.000     0.000     0.000     0.000
        Blow_Hole_2              0.000     0.000     0.000     0.000
        Stain_2                  0.000     0.000     0.000     0.000
        Dent_2                   0.000     0.000     0.000     0.000
        Deformation_2            0.000     0.000     0.000     0.000
        Contamination_2          0.000     0.000     0.000     0.000
        Impurity_2               0.000     0.000     0.000     0.000
        Crack_2                  0.000     0.000     0.000     0.000
        Scratch_2                0.000     0.000     0.000     0.000
        Buring_Mark_2            0.000     0.000     0.000     0.000
        Inclusions_2             0.000     0.000     0.000     0.000

                                  8         9     ...         7525  \
Process id                    8010.000  9011.000  ...  7525657.000
        Product_Type             1.000     1.000  ...        2.000
        Shot                    10.000    11.000  ...      657.000
        Velocity_1               0.142     0.144  ...        0.144
        Velocity_2               0.172     0.168  ...        0.173
        Velocity_3               0.176     0.184  ...        0.200
        High_Velocity            2.114     2.145  ...        2.536
        Cylinder_Pressure      217.000   217.000  ...      264.000
        Rapid_Rise_Time          0.008     0.008  ...        0.012
        Biscuit_Thickness       12.000    11.000  ...       17.000
        Clamping_Force         257.000   257.000  ...      381.000
        Cycle_Time              20.700    20.700  ...       36.300
         Pressure_Rise_Time      0.041     0.042  ...        0.036
        Casting_Pressure      1052.000  1051.000  ...      595.000
        Spray_Time               7.800     7.800  ...       12.100
        Spray_1_Time             0.700     0.700  ...        2.000
        Spray_2_Time             0.800     0.800  ...        2.000
Sensor  Melting_Furnace_Temp   699.600   701.400  ...      666.800
        Air_Pressure             6.400     6.500  ...        6.700
        Air_Pressure_Min         3.000     3.000  ...        3.000
        Air_Pressure_Max         9.000     9.000  ...        9.000
        Coolant_Temp            26.100    26.100  ...       28.100
        Coolant_Temp_Min        10.000    10.000  ...       10.000
        Coolant_Temp_Max        50.000    50.000  ...       50.000
        Coolant_Pressure         2.710     2.710  ...        2.630
        Factory_Temp            32.900    32.900  ...       32.400
        Factory_Temp_Min        18.000    18.000  ...       18.000
        Factory_Temp_Max        22.000    22.000  ...       22.000
        Factory_Humidity        57.800    57.900  ...       69.300
        Factory_Humidity_Min    18.000    18.000  ...       18.000
        Factory_Humidity_Max    22.000    22.000  ...       22.000
Defects Short_Shot_1             0.000     0.000  ...        0.000
        Bubble_1                 0.000     0.000  ...        0.000
        Exfoliation_1            0.000     0.000  ...        0.000
        Blow_Hole_1              0.000     0.000  ...        0.000
        Stain_1                  0.000     0.000  ...        0.000
        Dent_1                   0.000     0.000  ...        0.000
        Deformation_1            0.000     1.000  ...        0.000
        Contamination_1          0.000     0.000  ...        0.000
        Impurity_1               0.000     0.000  ...        0.000
        Crack_1                  0.000     0.000  ...        0.000
        Scratch_1                0.000     0.000  ...        0.000
        Buring_Mark_1            0.000     0.000  ...        0.000
        Inclusions_1             0.000     0.000  ...        0.000
        Short_Shot_2             0.000     0.000  ...        0.000
        Bubble_2                 0.000     0.000  ...        0.000
        Exfoliation_2            0.000     0.000  ...        0.000
        Blow_Hole_2              0.000     0.000  ...        0.000
        Stain_2                  0.000     0.000  ...        0.000
        Dent_2                   0.000     0.000  ...        0.000
        Deformation_2            0.000     0.000  ...        0.000
        Contamination_2          0.000     0.000  ...        0.000
        Impurity_2               0.000     0.000  ...        0.000
        Crack_2                  0.000     0.000  ...        0.000
        Scratch_2                0.000     0.000  ...        0.000
        Buring_Mark_2            0.000     0.000  ...        0.000
        Inclusions_2             0.000     0.000  ...        0.000

                                     7526         7527         7528  \
Process id                    7526657.000  7527658.000  7528658.000
        Product_Type                2.000        2.000        2.000
        Shot                      657.000      658.000      658.000
        Velocity_1                  0.144        0.144        0.144
        Velocity_2                  0.173        0.173        0.173
        Velocity_3                  0.200        0.200        0.200
        High_Velocity               2.536        2.536        2.536
        Cylinder_Pressure         264.000      264.000      264.000
        Rapid_Rise_Time             0.012        0.012        0.012
        Biscuit_Thickness          17.000       17.000       17.000
        Clamping_Force            381.000      381.000      381.000
        Cycle_Time                 36.300       36.300       36.300
         Pressure_Rise_Time         0.036        0.036        0.036
        Casting_Pressure          595.000      595.000      595.000
        Spray_Time                 12.100       12.100       12.100
        Spray_1_Time                2.000        2.000        2.000
        Spray_2_Time                2.000        2.000        2.000
Sensor  Melting_Furnace_Temp      666.800      667.400      667.400
        Air_Pressure                6.700        6.700        6.700
        Air_Pressure_Min            3.000        3.000        3.000
        Air_Pressure_Max            9.000        9.000        9.000
        Coolant_Temp               28.100       28.100       28.100
        Coolant_Temp_Min           10.000       10.000       10.000
        Coolant_Temp_Max           50.000       50.000       50.000
        Coolant_Pressure            2.630        2.620        2.620
        Factory_Temp               32.400       32.300       32.300
        Factory_Temp_Min           18.000       18.000       18.000
        Factory_Temp_Max           22.000       22.000       22.000
        Factory_Humidity           69.300       69.400       69.400
        Factory_Humidity_Min       18.000       18.000       18.000
        Factory_Humidity_Max       22.000       22.000       22.000
Defects Short_Shot_1                0.000        0.000        0.000
        Bubble_1                    0.000        0.000        0.000
        Exfoliation_1               0.000        0.000        0.000
        Blow_Hole_1                 0.000        0.000        0.000
        Stain_1                     0.000        0.000        0.000
        Dent_1                      0.000        0.000        0.000
        Deformation_1               0.000        0.000        0.000
        Contamination_1             0.000        0.000        0.000
        Impurity_1                  0.000        0.000        0.000
        Crack_1                     0.000        0.000        0.000
        Scratch_1                   0.000        0.000        0.000
        Buring_Mark_1               0.000        0.000        0.000
        Inclusions_1                0.000        0.000        0.000
        Short_Shot_2                0.000        0.000        0.000
        Bubble_2                    0.000        0.000        0.000
        Exfoliation_2               0.000        0.000        0.000
        Blow_Hole_2                 0.000        0.000        0.000
        Stain_2                     0.000        0.000        0.000
        Dent_2                      0.000        0.000        0.000
        Deformation_2               0.000        0.000        0.000
        Contamination_2             0.000        0.000        0.000
        Impurity_2                  0.000        0.000        0.000
        Crack_2                     0.000        0.000        0.000
        Scratch_2                   0.000        0.000        0.000
        Buring_Mark_2               0.000        0.000        0.000
        Inclusions_2                0.000        0.000        0.000

                                     7529         7530         7531  \
Process id                    7529659.000  7530659.000  7531660.000
        Product_Type                2.000        2.000        2.000
        Shot                      659.000      659.000      660.000
        Velocity_1                  0.150        0.150        0.144
        Velocity_2                  0.166        0.166        0.174
        Velocity_3                  0.210        0.210        0.206
        High_Velocity               2.492        2.492        2.514
        Cylinder_Pressure         265.000      265.000      264.000
        Rapid_Rise_Time             0.011        0.011        0.011
        Biscuit_Thickness          17.000       17.000       16.000
        Clamping_Force            381.000      381.000      381.000
        Cycle_Time                 36.200       36.200       36.200
         Pressure_Rise_Time         0.033        0.033        0.041
        Casting_Pressure          595.000      595.000      595.000
        Spray_Time                 12.100       12.100       12.100
        Spray_1_Time                2.000        2.000        2.000
        Spray_2_Time                2.000        2.000        2.000
Sensor  Melting_Furnace_Temp      667.400      667.400      667.800
        Air_Pressure                6.700        6.700        7.000
        Air_Pressure_Min            3.000        3.000        3.000
        Air_Pressure_Max            9.000        9.000        9.000
        Coolant_Temp               28.100       28.100       28.100
        Coolant_Temp_Min           10.000       10.000       10.000
        Coolant_Temp_Max           50.000       50.000       50.000
        Coolant_Pressure            2.620        2.620        2.620
        Factory_Temp               32.300       32.300       32.200
        Factory_Temp_Min           18.000       18.000       18.000
        Factory_Temp_Max           22.000       22.000       22.000
        Factory_Humidity           69.400       69.400       69.500
        Factory_Humidity_Min       18.000       18.000       18.000
        Factory_Humidity_Max       22.000       22.000       22.000
Defects Short_Shot_1                0.000        0.000        0.000
        Bubble_1                    0.000        0.000        0.000
        Exfoliation_1               0.000        0.000        0.000
        Blow_Hole_1                 0.000        0.000        1.000
        Stain_1                     0.000        0.000        0.000
        Dent_1                      0.000        0.000        0.000
        Deformation_1               0.000        0.000        0.000
        Contamination_1             0.000        0.000        0.000
        Impurity_1                  0.000        0.000        0.000
        Crack_1                     0.000        0.000        0.000
        Scratch_1                   0.000        0.000        0.000
        Buring_Mark_1               0.000        0.000        0.000
        Inclusions_1                0.000        0.000        0.000
        Short_Shot_2                0.000        0.000        0.000
        Bubble_2                    0.000        0.000        0.000
        Exfoliation_2               0.000        0.000        0.000
        Blow_Hole_2                 0.000        0.000        0.000
        Stain_2                     0.000        0.000        0.000
        Dent_2                      0.000        0.000        0.000
        Deformation_2               0.000        0.000        0.000
        Contamination_2             0.000        0.000        0.000
        Impurity_2                  0.000        0.000        0.000
        Crack_2                     0.000        0.000        0.000
        Scratch_2                   0.000        0.000        0.000
        Buring_Mark_2               0.000        0.000        0.000
        Inclusions_2                0.000        0.000        0.000

                                     7532         7533         7534
Process id                    7532660.000  7533661.000  7534661.000

In [29]:
### 컬럼 속 공백 제거

In [30]:
df_copy.rename(columns={'Biscuit_Thickness ': 'Biscuit_Thickness', 'Clamping_Force ': 'Clamping_Force', ' Pressure_Rise_Time': 'Pressure_Rise_Time'}, level=1, inplace=True)

In [31]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 7535 entries, 0 to 7534
Data columns (total 57 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   (Process, id)                   7535 non-null   int64
 1   (Process, Product_Type)         7535 non-null   int64
 2   (Process, Shot)                 7535 non-null   int64
 3   (Process, Velocity_1)           7535 non-null   float64
 4   (Process, Velocity_2)           7535 non-null   float64
 5   (Process, Velocity_3)           7535 non-null   float64
 6   (Process, High_Velocity)        7535 non-null   float64
 7   (Process, Cylinder_Pressure)    7535 non-null   int64
 8   (Process, Rapid_Rise_Time)      7535 non-null   float64
 9   (Process, Biscuit_Thickness)    7535 non-null   int64
 10  (Process, Clamping_Force)       7535 non-null   int64
 11  (Process, Cycle_Time)           7535 non-null   float64
 12  (Process, Pressure_Rise_Time)   7535 non-null   float64
 13  (Process, Casting_Pressure)     7535 non-null   int64
 14  (Process, Spray_Time)           7535 non-null   float64
 15  (Process, Spray_1_Time)         7535 non-null   float64
 16  (Process, Spray_2_Time)         7535 non-null   float64
 17  (Sensor, Melting_Furnace_Temp)  7535 non-null   float64
 18  (Sensor, Air_Pressure)          7535 non-null   float64
 19  (Sensor, Air_Pressure_Min)      7535 non-null   int64
 20  (Sensor, Air_Pressure_Max)      7535 non-null   int64
 21  (Sensor, Coolant_Temp)          7535 non-null   float64
 22  (Sensor, Coolant_Temp_Min)      7535 non-null   int64
 23  (Sensor, Coolant_Temp_Max)      7535 non-null   int64
 24  (Sensor, Coolant_Pressure)      7535 non-null   float64
 25  (Sensor, Factory_Temp)          7535 non-null   float64
 26  (Sensor, Factory_Temp_Min)      7535 non-null   float64
 27  (Sensor, Factory_Temp_Max)      7535 non-null   float64
 28  (Sensor, Factory_Humidity)      7535 non-null   float64
 29  (Sensor, Factory_Humidity_Min)  7535 non-null   float64
 30  (Sensor, Factory_Humidity_Max)  7535 non-null   float64
 31  (Defects, Short_Shot_1)         7535 non-null   int64
 32  (Defects, Bubble_1)             7535 non-null   int64
 33  (Defects, Exfoliation_1)        7535 non-null   int64
 34  (Defects, Blow_Hole_1)          7535 non-null   int64
 35  (Defects, Stain_1)              7535 non-null   int64
 36  (Defects, Dent_1)               7535 non-null   int64
 37  (Defects, Deformation_1)        7535 non-null   int64
 38  (Defects, Contamination_1)      7535 non-null   int64
 39  (Defects, Impurity_1)           7535 non-null   int64
 40  (Defects, Crack_1)              7535 non-null   int64
 41  (Defects, Scratch_1)            7535 non-null   int64
 42  (Defects, Buring_Mark_1)        7535 non-null   int64
 43  (Defects, Inclusions_1)         7535 non-null   int64
 44  (Defects, Short_Shot_2)         7535 non-null   int64
 45  (Defects, Bubble_2)             7535 non-null   int64
 46  (Defects, Exfoliation_2)        7535 non-null   int64
 47  (Defects, Blow_Hole_2)          7535 non-null   int64
 48  (Defects, Stain_2)              7535 non-null   int64
 49  (Defects, Dent_2)               7535 non-null   int64
 50  (Defects, Deformation_2)        7535 non-null   int64
 51  (Defects, Contamination_2)      7535 non-null   int64
 52  (Defects, Impurity_2)           7535 non-null   int64
 53  (Defects, Crack_2)              7535 non-null   int64
 54  (Defects, Scratch_2)            7535 non-null   int64
 55  (Defects, Buring_Mark_2)        7535 non-null   int64
 56  (Defects, Inclusions_2)         7535 non-null   int64
dtypes: float64(20), int64(37)
memory usage: 3.3 MB

In [32]:
df_copy.isna().sum()

Process  id                      0
         Product_Type            0
         Shot                    0
         Velocity_1              0
         Velocity_2              0
         Velocity_3              0
         High_Velocity           0
         Cylinder_Pressure       0
         Rapid_Rise_Time         0
         Biscuit_Thickness       0
         Clamping_Force          0
         Cycle_Time              0
         Pressure_Rise_Time      0
         Casting_Pressure        0
         Spray_Time              0
         Spray_1_Time            0
         Spray_2_Time            0
Sensor   Melting_Furnace_Temp    0
         Air_Pressure            0
         Air_Pressure_Min        0
         Air_Pressure_Max        0
         Coolant_Temp            0
         Coolant_Temp_Min        0
         Coolant_Temp_Max        0
         Coolant_Pressure        0
         Factory_Temp            0
         Factory_Temp_Min        0
         Factory_Temp_Max        0
         Factory_Humidity        0
         Factory_Humidity_Min    0
         Factory_Humidity_Max    0
Defects  Short_Shot_1            0
         Bubble_1                0
         Exfoliation_1           0
         Blow_Hole_1             0
         Stain_1                 0
         Dent_1                  0
         Deformation_1           0
         Contamination_1         0
         Impurity_1              0
         Crack_1                 0
         Scratch_1               0
         Buring_Mark_1           0
         Inclusions_1            0
         Short_Shot_2            0
         Bubble_2                0
         Exfoliation_2           0
         Blow_Hole_2             0
         Stain_2                 0
         Dent_2                  0
         Deformation_2           0
         Contamination_2         0
         Impurity_2              0
         Crack_2                 0
         Scratch_2               0
         Buring_Mark_2           0
         Inclusions_2            0
dtype: int64